# Generated by Django 4.2.7 on 2025-08-07 03:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "did",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_profiles",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Profile",
                "verbose_name_plural": "Smart Profiles",
                "db_table": "smart_profile",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="VerifiableCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("credential_data", models.JSONField()),
                ("issuer_did", models.CharField(max_length=255)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="core.smartprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verifiable Credential",
                "verbose_name_plural": "Verifiable Credentials",
                "db_table": "verifiable_credential",
            },
        ),
        migrations.AlterUniqueTogether(
            name="communitymembership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="communitymembership",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_memberships",
                to="core.smartprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymembership",
            unique_together={("profile", "world")},
        ),
        migrations.RemoveField(
            model_name="communitymembership",
            name="user",
        ),
    ]
